WITH SELLER_RANK AS (

    SELECT
        SELLER_ID,
        SELLER_CITY,
        SELLER_STATE,
        DELIVERED_ORDERS,
        LATE_ORDERS,
        REVENUE,
        AVG_REVIEW_SCORE,
        LATE_RATE,

        RANK() OVER (
            PARTITION BY SELLER_STATE
            ORDER BY LATE_RATE DESC
        ) AS STATE_LATE_RANK

    FROM RETAILLENS_2328073.ANALYTICS.SELLER_PERFORMANCE

    WHERE DELIVERED_ORDERS >= 20
)

SELECT
    SELLER_ID,
    SELLER_CITY,
    SELLER_STATE,
    DELIVERED_ORDERS,
    LATE_ORDERS,
    ROUND(LATE_RATE * 100, 2) AS LATE_RATE_PERCENT,
    ROUND(AVG_REVIEW_SCORE, 2) AS AVG_REVIEW_SCORE,
    ROUND(REVENUE, 2) AS REVENUE,
    STATE_LATE_RANK
FROM SELLER_RANK
ORDER BY LATE_RATE DESC, DELIVERED_ORDERS DESC;