SELECT
    CATEGORY,
    ORDERS,
    ROUND(AVG_DELIVERY_DAYS, 2) AS AVG_DELIVERY_DAYS,
    ROUND(LATE_RATE * 100, 2) AS LATE_RATE_PERCENT,
    ROUND(AVG_REVIEW_SCORE, 2) AS AVG_REVIEW_SCORE,
    ROUND(LATE_AVG_REVIEW_SCORE, 2) AS LATE_REVIEW_SCORE,
    ROUND(ON_TIME_AVG_REVIEW_SCORE, 2) AS ON_TIME_REVIEW_SCORE,
    ROUND(REVIEW_SCORE_GAP, 2) AS REVIEW_SCORE_GAP
FROM RETAILLENS_2328073.ANALYTICS.CATEGORY_DELIVERY_REVIEW
WHERE ORDERS >= 50
ORDER BY REVIEW_SCORE_GAP DESC, LATE_RATE_PERCENT DESC;