SELECT
    QUARTER,
    TOTAL_ORDERS,
    ROUND(TOTAL_REVENUE, 2) AS TOTAL_REVENUE,
    REPEAT_ORDERS,
    ROUND(REPEAT_REVENUE, 2) AS REPEAT_REVENUE,
    ROUND(REPEAT_REVENUE_SHARE * 100, 2) AS REPEAT_REVENUE_PERCENT
FROM RETAILLENS_2328073.ANALYTICS.REPEAT_CUSTOMER_QUARTER
ORDER BY QUARTER;