SELECT
    COUNT(*) AS ELIGIBLE_SELLERS,
    ROUND(
        CORR(LATE_RATE, AVG_REVIEW_SCORE),
        3
    ) AS LATE_RATE_REVIEW_CORRELATION
FROM RETAILLENS_2328073.ANALYTICS.SELLER_PERFORMANCE
WHERE DELIVERED_ORDERS >= 20;